In [24]:
import numpy as np

##### Exercise 1: Return odd rows and even columns

In [2]:
sample = np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])

In [3]:
sample

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [4]:
odd_rows_even_columns = sample[::2,1::2]
odd_rows_even_columns

array([[ 6, 12],
       [30, 36],
       [54, 60]])

##### Excercise 2: 

In [6]:
arrayOne = np.array([[5,6,9],[21,18,27]])
arrayTwo = np.array([[15,33,24],[4,7,1]])

In [8]:
sum_arrays = arrayOne+arrayTwo

In [34]:
sqrt_sum = np.square(sum_arrays)
sqrt_sum

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

#### Exercise 3: Delete and Insert

In [52]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
newColumn


array([[10, 10, 10]])

In [56]:
sampleArray = sampleArray[:,0::2]

array([[34, 73],
       [82, 12],
       [53, 66]])

In [57]:
sampleArray[:,1::2] = np.transpose(newColumn)

In [58]:
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

##### Exercise 4: sorting by row and column

###### sorting by second row

In [99]:
sampleArray2 = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray2)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [100]:
sorting_index_1 = sampleArray2[1].argsort()
print(sorting_index_1)

[2 1 0]


In [101]:
sorted_by_row = sampleArray2[:,sorting_index]
print(sorted_by_row)

[[73 43 34]
 [12 22 82]
 [66 94 53]]


###### sorting by second column

In [97]:
print(sampleArray2)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [104]:

sorting_index_2 = sampleArray2[:,1].argsort()
print(sorting_index_2)

[2 1 0]


In [96]:
sorted_2_column = sampleArray2[sorting_index]
print(sorted_2_column)

[[82 22 12]
 [34 43 73]
 [53 94 66]]


##### Exercise 5

In [19]:
Z = [2, 3, 6, 7, 9, 8, 4, 7, 9, 2, 1, 0, 4]
# for i in range(len(Z)):
#     if Z[i]>=3 and Z[i] <=8:
#         Z[i] = int('-'+str(Z[i]))
        
# print(Z)

In [32]:
Z = np.array(Z)
a = np.where(np.logical_and(Z>3,Z < 8),-Z,Z)
a

array([ 2, -3, -6, -7,  9, -8, -4, -7,  9,  2,  1,  0, -4])