##### Exercise 1

Generate a 10 x 3 array of random numbers (in range [0,1]

In [51]:
ranNum = np.random.random(30)


In [54]:
ranNum = ranNum.reshape(10,3)


In [100]:
ranNum

array([[0.41661487, 0.3835787 , 0.37951521],
       [0.51421529, 0.16965253, 0.58714317],
       [0.87104174, 0.60619355, 0.72130881],
       [0.71544827, 0.10811338, 0.35514347],
       [0.882992  , 0.84227257, 0.91903473],
       [0.03061783, 0.02860649, 0.63162084],
       [0.94188722, 0.00103836, 0.61841725],
       [0.65510884, 0.10278709, 0.20018624],
       [0.22338649, 0.05863427, 0.54608343],
       [0.63976507, 0.83711222, 0.05923676]])

In [55]:
ranNum.shape

(10, 3)

For each element, compute the distance to 0.5.

In [56]:
dis_to = abs(ranNum-0.5)

In [73]:
dis_to

array([[0.08338513, 0.1164213 , 0.12048479],
       [0.01421529, 0.33034747, 0.08714317],
       [0.37104174, 0.10619355, 0.22130881],
       [0.21544827, 0.39188662, 0.14485653],
       [0.382992  , 0.34227257, 0.41903473],
       [0.46938217, 0.47139351, 0.13162084],
       [0.44188722, 0.49896164, 0.11841725],
       [0.15510884, 0.39721291, 0.29981376],
       [0.27661351, 0.44136573, 0.04608343],
       [0.13976507, 0.33711222, 0.44076324]])

return the indices that would sort an array (closest to farthest from 0.5 – horizontally) 

In [110]:
sort_far_hor = np.argsort(dis_to,axis=1)

In [125]:
sort_far_hor

array([[0, 1, 2],
       [0, 2, 1],
       [1, 2, 0],
       [2, 0, 1],
       [1, 0, 2],
       [2, 0, 1],
       [2, 0, 1],
       [0, 2, 1],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

In [151]:
# np.argmin(dis_to,axis=1)

min_index = sort_far_hor[:,0:1]

In [138]:
 sort_far_hor_index = min_index.flatten()

In [149]:
# closest_val = []
ranNum[9][sort_far_hor_index[9]]

0.6397650685994237

In [166]:
# for a in range(10):
#     closest_val[a] = ranNum[a][sort_far_hor_index[a]]
# #     print(closest_val)

ranNum[:,sort_far_hor_index]

array([[0.41661487, 0.41661487, 0.3835787 , 0.37951521, 0.3835787 ,
        0.37951521, 0.37951521, 0.41661487, 0.37951521, 0.41661487],
       [0.51421529, 0.51421529, 0.16965253, 0.58714317, 0.16965253,
        0.58714317, 0.58714317, 0.51421529, 0.58714317, 0.51421529],
       [0.87104174, 0.87104174, 0.60619355, 0.72130881, 0.60619355,
        0.72130881, 0.72130881, 0.87104174, 0.72130881, 0.87104174],
       [0.71544827, 0.71544827, 0.10811338, 0.35514347, 0.10811338,
        0.35514347, 0.35514347, 0.71544827, 0.35514347, 0.71544827],
       [0.882992  , 0.882992  , 0.84227257, 0.91903473, 0.84227257,
        0.91903473, 0.91903473, 0.882992  , 0.91903473, 0.882992  ],
       [0.03061783, 0.03061783, 0.02860649, 0.63162084, 0.02860649,
        0.63162084, 0.63162084, 0.03061783, 0.63162084, 0.03061783],
       [0.94188722, 0.94188722, 0.00103836, 0.61841725, 0.00103836,
        0.61841725, 0.61841725, 0.94188722, 0.61841725, 0.94188722],
       [0.65510884, 0.65510884, 0.1027870

###### Exercise 2

In [156]:
div = np.array([5,4,6,10,24,89,45,43,46,99,100])

##### Not divisible by 3

In [159]:
not_div_3 = div[div%3 == 1]

In [160]:
div_3

array([  4,  10,  43,  46, 100])

##### Divisible by 5

In [161]:
div_5 = div[div % 5 == 0]
div_5

array([  5,  10,  45, 100])

##### Divisible by 3 and 5

In [162]:
div_3_and_5 = div[np.logical_and(div % 3 == 0,div % 5 == 0)]

In [163]:
div_3_and_5

array([45])

##### Divisible by 3 and set them to 42

In [164]:
div_3_to_42 = np.where(div % 3 == 0,42,div)

In [165]:
div_3_to_42

array([  5,   4,  42,  10,  42,  89,  42,  43,  46,  42, 100])

#### Exercise 3

##### Calculate the prime numbers between 0 and 100 by using a Boolean array